# Student Performance Data — Cleaning

Loads the raw dataset, standardizes column names, checks for missing values and duplicates, and writes a clean CSV for downstream analysis and the dashboard app.

## 1. Load the raw data

`DATA_PATH` points at the source CSV. Cleaning is idempotent: running this notebook again on already-clean data is safe and simply re-saves the same result.

In [1]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/study.csv")

df = pd.read_csv(DATA_PATH, encoding="latin1", on_bad_lines="skip")
print(df.shape)
df.head()

(1000, 8)

,Gender,Race,Parental Level of Education,Lunch,Preparation Course,Mathematics Score,Reading Score,Writing Score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## 2. Inspect the data

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gender                       1000 non-null   str
 1   Race                         1000 non-null   str
 2   Parental Level of Education  1000 non-null   str
 3   Lunch                        1000 non-null   str
 4   Preparation Course           1000 non-null   str
 5   Mathematics Score            1000 non-null   int64
 6   Reading Score                1000 non-null   int64
 7   Writing Score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

In [3]:
df.describe()

       Mathematics Score  Reading Score  Writing Score
count         1000.00000    1000.000000    1000.000000
mean            66.08900      69.169000      68.054000
std             15.16308      14.600192      15.195657
min              0.00000      17.000000      10.000000
25%             57.00000      59.000000      57.750000
50%             66.00000      70.000000      69.000000
75%             77.00000      79.000000      79.000000
max            100.00000     100.000000     100.000000

## 3. Missing values and duplicates

In [4]:
print("Missing values per column:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Missing values per column:
Gender                         0
Race                           0
Parental Level of Education    0
Lunch                          0
Preparation Course             0
Mathematics Score              0
Reading Score                  0
Writing Score                  0
dtype: int64

Duplicate rows: 0

In [5]:
# Drop any missing rows and exact duplicates
df = df.dropna()
df = df.drop_duplicates()
print(df.shape)

(1000, 8)

## 4. Standardize column names

Renames raw source columns (snake_case) to the consistent, human-readable labels used throughout the notebooks and the dashboard. Columns already in the target format are left untouched, so this step is safe to re-run.

In [6]:
df = df.rename(columns={
    "gender": "Gender",
    "race_ethnicity": "Race",
    "parental_level_of_education": "Parental Level of Education",
    "lunch": "Lunch",
    "test_preparation_course": "Preparation Course",
    "math_score": "Mathematics Score",
    "reading_score": "Reading Score",
    "writing_score": "Writing Score",
})

# Drop stray 'Unnamed: 0' style index columns from earlier exports
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
df.head()

,Gender,Race,Parental Level of Education,Lunch,Preparation Course,Mathematics Score,Reading Score,Writing Score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

## 5. Final check and export

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gender                       1000 non-null   str
 1   Race                         1000 non-null   str
 2   Parental Level of Education  1000 non-null   str
 3   Lunch                        1000 non-null   str
 4   Preparation Course           1000 non-null   str
 5   Mathematics Score            1000 non-null   int64
 6   Reading Score                1000 non-null   int64
 7   Writing Score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 103.5 KB

In [8]:
DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(DATA_PATH, index=False)
print(f"Saved cleaned data to {DATA_PATH.resolve()}")

Saved cleaned data to D:\githubslop\student-performance-dashboard(refurbished)\data\study.csv